credentials:
  usernames:
    admin:
      email: admin@rentcal.com
      failed_login_attempts: 0
      logged_in: false
      name: Administrator
      password: $2b$12$F5tjAyYOz/MG/WGhisqBtejU4xxLW92fkBEwvrv14dzrOIehTBhnq  # Default: admin123 (CHANGE THIS!)
    user:
      email: user@rentcal.com
      failed_login_attempts: 0
      logged_in: false
      name: User
      password: $2b$12$F5tjAyYOz/MG/WGhisqBtejU4xxLW92fkBEwvrv14dzrOIehTBhnq  # Default: admin123 (CHANGE THIS!)
cookie:
  expiry_days: 30
  key: rentcal_auth_key  # Random key for cookie encoding (CHANGE THIS!)
  name: rentcal_cookie
preauthorized:
  emails:
    - admin@rentcal.com

